version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
      JAVA_HOME: C:\Program Files\Java\jdk-11
    steps:
      - checkout

      - run:
          name: Set execution permission for gradlew
          command: chmod +x gradlew

      - run:
          name: Display Java version
          command: java -version

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - run:
          name: Clean project
          command: ./gradlew clean

      - run:
          name: Build project
          command: bash -c "./gradlew assembleDebug --warning-mode all"

      - run:
          name: Run unit tests
          command: bash -c "./gradlew testDebugUnitTest"

      - save_cache:
          key: jars-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks

workflows:
  version: 2
  build-deploy:
    jobs: 
      - build
